/* IDT setup: creates interrupt gate entries and loads the table
 *
 * Each IDT entry is 64 bits describing an interrupt gate:
 *   - offset (handler address) split into low 16 and high 16 bits
 *   - segment selector (kernel code segment = 0x08)
 *   - type/attributes: present, DPL 0, 32-bit interrupt gate
 */

#include "idt.h"
#include "pic.h"
#include "keyboard.h"
#include "process.h"
#include "io.h"
#include "fb.h"

#define IDT_NUM_ENTRIES 256
#define KERNEL_CODE_SEGMENT 0x08

/* IDT entry (interrupt gate descriptor) */
struct idt_entry {
    unsigned short offset_low;      /* lower 16 bits of handler address */
    unsigned short segment_sel;     /* kernel code segment selector */
    unsigned char  reserved;        /* always 0 */
    unsigned char  type_attr;       /* type and attributes (P, DPL, gate type) */
    unsigned short offset_high;     /* upper 16 bits of handler address */
} __attribute__((packed));

/* IDT pointer passed to lidt */
struct idt_ptr {
    unsigned short limit;           /* size of IDT - 1 */
    unsigned int   base;            /* address of first entry */
} __attribute__((packed));

/* assembly function that executes lidt */
extern void load_idt(struct idt_ptr *ptr);

/* assembly handler labels (generated by macros in interrupt_handlers.s) */
extern void interrupt_handler_0(void);
extern void interrupt_handler_1(void);
extern void interrupt_handler_2(void);
extern void interrupt_handler_3(void);
extern void interrupt_handler_4(void);
extern void interrupt_handler_5(void);
extern void interrupt_handler_6(void);
extern void interrupt_handler_7(void);
extern void interrupt_handler_8(void);
extern void interrupt_handler_9(void);
extern void interrupt_handler_10(void);
extern void interrupt_handler_11(void);
extern void interrupt_handler_12(void);
extern void interrupt_handler_13(void);
extern void interrupt_handler_14(void);
extern void interrupt_handler_15(void);
extern void interrupt_handler_16(void);
extern void interrupt_handler_17(void);
extern void interrupt_handler_18(void);
extern void interrupt_handler_19(void);
extern void interrupt_handler_20(void);
extern void interrupt_handler_21(void);
extern void interrupt_handler_22(void);
extern void interrupt_handler_23(void);
extern void interrupt_handler_24(void);
extern void interrupt_handler_25(void);
extern void interrupt_handler_26(void);
extern void interrupt_handler_27(void);
extern void interrupt_handler_28(void);
extern void interrupt_handler_29(void);
extern void interrupt_handler_30(void);
extern void interrupt_handler_31(void);
extern void interrupt_handler_32(void);
extern void interrupt_handler_33(void);
extern void interrupt_handler_34(void);
extern void interrupt_handler_35(void);
extern void interrupt_handler_36(void);
extern void interrupt_handler_37(void);
extern void interrupt_handler_38(void);
extern void interrupt_handler_39(void);
extern void interrupt_handler_40(void);
extern void interrupt_handler_41(void);
extern void interrupt_handler_42(void);
extern void interrupt_handler_43(void);
extern void interrupt_handler_44(void);
extern void interrupt_handler_45(void);
extern void interrupt_handler_46(void);
extern void interrupt_handler_47(void);

extern void syscall_handler_128(void);

static struct idt_entry idt[IDT_NUM_ENTRIES];

/* CPU state pushed by the common interrupt handler */
struct cpu_state {
    unsigned int ebp;
    unsigned int edi;
    unsigned int esi;
    unsigned int edx;
    unsigned int ecx;
    unsigned int ebx;
    unsigned int eax;
} __attribute__((packed));

/* Stack state pushed by CPU on interrupt */
struct stack_state {
    unsigned int error_code;
    unsigned int eip;
    unsigned int cs;
    unsigned int eflags;
} __attribute__((packed));

/* Set a single IDT entry */
static void idt_set_entry(unsigned int index, unsigned int handler,
                          unsigned short sel, unsigned char type_attr)
{
    idt[index].offset_low  = handler & 0xFFFF;
    idt[index].offset_high = (handler >> 16) & 0xFFFF;
    idt[index].segment_sel = sel;
    idt[index].reserved    = 0;
    idt[index].type_attr   = type_attr;
}

/* Helper: build an array of handler addresses for easy iteration */
static void idt_install_handlers(void)
{
    /* type_attr: present=1, DPL=0, 32-bit interrupt gate = 0x8E */
    unsigned char attr = 0x8E;

    idt_set_entry(0,  (unsigned int)interrupt_handler_0,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(1,  (unsigned int)interrupt_handler_1,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(2,  (unsigned int)interrupt_handler_2,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(3,  (unsigned int)interrupt_handler_3,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(4,  (unsigned int)interrupt_handler_4,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(5,  (unsigned int)interrupt_handler_5,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(6,  (unsigned int)interrupt_handler_6,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(7,  (unsigned int)interrupt_handler_7,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(8,  (unsigned int)interrupt_handler_8,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(9,  (unsigned int)interrupt_handler_9,  KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(10, (unsigned int)interrupt_handler_10, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(11, (unsigned int)interrupt_handler_11, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(12, (unsigned int)interrupt_handler_12, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(13, (unsigned int)interrupt_handler_13, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(14, (unsigned int)interrupt_handler_14, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(15, (unsigned int)interrupt_handler_15, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(16, (unsigned int)interrupt_handler_16, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(17, (unsigned int)interrupt_handler_17, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(18, (unsigned int)interrupt_handler_18, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(19, (unsigned int)interrupt_handler_19, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(20, (unsigned int)interrupt_handler_20, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(21, (unsigned int)interrupt_handler_21, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(22, (unsigned int)interrupt_handler_22, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(23, (unsigned int)interrupt_handler_23, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(24, (unsigned int)interrupt_handler_24, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(25, (unsigned int)interrupt_handler_25, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(26, (unsigned int)interrupt_handler_26, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(27, (unsigned int)interrupt_handler_27, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(28, (unsigned int)interrupt_handler_28, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(29, (unsigned int)interrupt_handler_29, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(30, (unsigned int)interrupt_handler_30, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(31, (unsigned int)interrupt_handler_31, KERNEL_CODE_SEGMENT, attr);

    /* IRQs 0-15 remapped to 32-47 */
    idt_set_entry(32, (unsigned int)interrupt_handler_32, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(33, (unsigned int)interrupt_handler_33, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(34, (unsigned int)interrupt_handler_34, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(35, (unsigned int)interrupt_handler_35, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(36, (unsigned int)interrupt_handler_36, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(37, (unsigned int)interrupt_handler_37, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(38, (unsigned int)interrupt_handler_38, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(39, (unsigned int)interrupt_handler_39, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(40, (unsigned int)interrupt_handler_40, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(41, (unsigned int)interrupt_handler_41, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(42, (unsigned int)interrupt_handler_42, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(43, (unsigned int)interrupt_handler_43, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(44, (unsigned int)interrupt_handler_44, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(45, (unsigned int)interrupt_handler_45, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(46, (unsigned int)interrupt_handler_46, KERNEL_CODE_SEGMENT, attr);
    idt_set_entry(47, (unsigned int)interrupt_handler_47, KERNEL_CODE_SEGMENT, attr);

    /* System call: DPL=3 so user mode can invoke via int 0x80 */
    idt_set_entry(0x80, (unsigned int)syscall_handler_128, KERNEL_CODE_SEGMENT, 0xEE);
}

/* Despacho C (comum a todas as interrupções): dispositivos, EOI, preempção. */
void interrupt_handler(struct cpu_state cpu, unsigned int int_no,
                       struct stack_state stack)
{
    (void)cpu;

    if (int_no == 33) {
        keyboard_handler();
    }

    /* EOI antes de schedule (timer pode não retornar “logo”). */
    if (int_no >= 32 && int_no <= 47) {
        pic_acknowledge(int_no);
    }

    /* IRQ0 + CPL=3: tick do PIT → próximo processo pronto. */
    if (int_no == 32 && (stack.cs & 0x3) == 3) {
        schedule();
    }
}

/* Initialize IDT, remap PIC, enable interrupts */
void idt_init(void)
{
    /* zero out all entries first */
    unsigned int i;
    for (i = 0; i < IDT_NUM_ENTRIES; i++) {
        idt_set_entry(i, 0, 0, 0);
    }

    /* remap PIC so IRQs don't clash with CPU exceptions */
    pic_remap();

    /* install all handlers */
    idt_install_handlers();

    /* load the IDT */
    struct idt_ptr ptr;
    ptr.limit = sizeof(idt) - 1;
    ptr.base  = (unsigned int)&idt;
    load_idt(&ptr);

    /* enable interrupts */
    __asm__ __volatile__("sti");
}
